image: docker:stable

services:
  - name: docker:dind
    command: ["--insecure-registry=registry.cicd.claimh.com:5000"]

stages:
  - publish

variables:
  DOCKER_DRIVER: overlay
  NPM_REGISTRY_URI: registry.cicd.claimh.com:6000

publish:
  stage: publish
  image: node:10.14.2-alpine
  before_script:
  - sed -i'' -r 's/^( +, uidSupport = ).+$/\1false/' $(dirname $(dirname $(which npm)))/lib/node_modules/npm/node_modules/uid-number/uid-number.js
  script:
<<<<<<< HEAD
  - npm unpublish -f flatory --registry=http://$NPM_REGISTRY_URI/
  - npm publish --registry=http://$NPM_REGISTRY_URI/
=======
  - npm unpublish -f flatory --registry=http://$NPM_REGISTRY_URI
  - npm publish --registry=http://$NPM_REGISTRY_URI
>>>>>>> 724d49c70dbac3c6ede0c5c980b440bc9c223459
  only:
  - master
