image: node:10.14.2-alpine

stages:
  - publish

variables:
  GIT_SSL_NO_VERIFY: "true"
  DOCKER_DRIVER: overlay2
  NPM_REGISTRY_URI: "npm.claimh.com"

publish:
  stage: publish
  before_script:
  - sed -i'' -r 's/^( +, uidSupport = ).+$/\1false/' $(dirname $(dirname $(which npm)))/lib/node_modules/npm/node_modules/uid-number/uid-number.js
  script:
  - npm publish -f --registry=https://$NPM_REGISTRY_URI/
  only:
  - master
